from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class KnowledgeCreate(BaseModel):
    """Manual knowledge entry created by admin"""
    title: str
    content: str
    question: Optional[str] = None  # Q&A format: "What is your experience?"
    answer: Optional[str] = None    # Q&A format answer
    category: str = "general"
    is_active: bool = True
    source_type: str = "manual"     # "manual" or "auto" (auto = from projects)
    project_id: Optional[str] = None  # Link to projects table if auto-generated

class KnowledgeUpdate(BaseModel):
    """Update existing knowledge entry"""
    title: Optional[str] = None
    content: Optional[str] = None
    question: Optional[str] = None
    answer: Optional[str] = None
    category: Optional[str] = None
    is_active: Optional[bool] = None
    source_type: Optional[str] = None
    project_id: Optional[str] = None

class KnowledgeAutoGenerated(BaseModel):
    """Auto-generated knowledge from a project"""
    title: str
    question: str = "Tell me about this project"
    answer: str  # Generated from project title + description + tech
    category: str = "projects"
    is_active: bool = True
    source_type: str = "auto"
    project_id: str
